# Generated by Django 2.2 on 2020-07-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
